/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogWebsocketReconnectBackoffRouteImport } from './routes/blog/websocket-reconnect-backoff'
import { Route as BlogTanstackRouterUrlStateRouteImport } from './routes/blog/tanstack-router-url-state'
import { Route as BlogReactFetchRaceConditionRouteImport } from './routes/blog/react-fetch-race-condition'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWebsocketReconnectBackoffRoute =
  BlogWebsocketReconnectBackoffRouteImport.update({
    id: '/blog/websocket-reconnect-backoff',
    path: '/blog/websocket-reconnect-backoff',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTanstackRouterUrlStateRoute =
  BlogTanstackRouterUrlStateRouteImport.update({
    id: '/blog/tanstack-router-url-state',
    path: '/blog/tanstack-router-url-state',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogReactFetchRaceConditionRoute =
  BlogReactFetchRaceConditionRouteImport.update({
    id: '/blog/react-fetch-race-condition',
    path: '/blog/react-fetch-race-condition',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/react-fetch-race-condition': typeof BlogReactFetchRaceConditionRoute
  '/blog/tanstack-router-url-state': typeof BlogTanstackRouterUrlStateRoute
  '/blog/websocket-reconnect-backoff': typeof BlogWebsocketReconnectBackoffRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/react-fetch-race-condition': typeof BlogReactFetchRaceConditionRoute
  '/blog/tanstack-router-url-state': typeof BlogTanstackRouterUrlStateRoute
  '/blog/websocket-reconnect-backoff': typeof BlogWebsocketReconnectBackoffRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/react-fetch-race-condition': typeof BlogReactFetchRaceConditionRoute
  '/blog/tanstack-router-url-state': typeof BlogTanstackRouterUrlStateRoute
  '/blog/websocket-reconnect-backoff': typeof BlogWebsocketReconnectBackoffRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/blog/react-fetch-race-condition'
    | '/blog/tanstack-router-url-state'
    | '/blog/websocket-reconnect-backoff'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/blog/react-fetch-race-condition'
    | '/blog/tanstack-router-url-state'
    | '/blog/websocket-reconnect-backoff'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/blog/react-fetch-race-condition'
    | '/blog/tanstack-router-url-state'
    | '/blog/websocket-reconnect-backoff'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogReactFetchRaceConditionRoute: typeof BlogReactFetchRaceConditionRoute
  BlogTanstackRouterUrlStateRoute: typeof BlogTanstackRouterUrlStateRoute
  BlogWebsocketReconnectBackoffRoute: typeof BlogWebsocketReconnectBackoffRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/websocket-reconnect-backoff': {
      id: '/blog/websocket-reconnect-backoff'
      path: '/blog/websocket-reconnect-backoff'
      fullPath: '/blog/websocket-reconnect-backoff'
      preLoaderRoute: typeof BlogWebsocketReconnectBackoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tanstack-router-url-state': {
      id: '/blog/tanstack-router-url-state'
      path: '/blog/tanstack-router-url-state'
      fullPath: '/blog/tanstack-router-url-state'
      preLoaderRoute: typeof BlogTanstackRouterUrlStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/react-fetch-race-condition': {
      id: '/blog/react-fetch-race-condition'
      path: '/blog/react-fetch-race-condition'
      fullPath: '/blog/react-fetch-race-condition'
      preLoaderRoute: typeof BlogReactFetchRaceConditionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogReactFetchRaceConditionRoute: BlogReactFetchRaceConditionRoute,
  BlogTanstackRouterUrlStateRoute: BlogTanstackRouterUrlStateRoute,
  BlogWebsocketReconnectBackoffRoute: BlogWebsocketReconnectBackoffRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
