/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as BlogLatticeBackendDddRefactorRouteImport } from './routes/blog/lattice-backend-ddd-refactor'
import { Route as BlogConfigureAlacrittyFromScratchRouteImport } from './routes/blog/configure-alacritty-from-scratch'
import { Route as BlogBuildPersonalBlogWithNextjsAndMdxRouteImport } from './routes/blog/build-personal-blog-with-nextjs-and-mdx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLatticeBackendDddRefactorRoute =
  BlogLatticeBackendDddRefactorRouteImport.update({
    id: '/blog/lattice-backend-ddd-refactor',
    path: '/blog/lattice-backend-ddd-refactor',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogConfigureAlacrittyFromScratchRoute =
  BlogConfigureAlacrittyFromScratchRouteImport.update({
    id: '/blog/configure-alacritty-from-scratch',
    path: '/blog/configure-alacritty-from-scratch',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBuildPersonalBlogWithNextjsAndMdxRoute =
  BlogBuildPersonalBlogWithNextjsAndMdxRouteImport.update({
    id: '/blog/build-personal-blog-with-nextjs-and-mdx',
    path: '/blog/build-personal-blog-with-nextjs-and-mdx',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/build-personal-blog-with-nextjs-and-mdx': typeof BlogBuildPersonalBlogWithNextjsAndMdxRoute
  '/blog/configure-alacritty-from-scratch': typeof BlogConfigureAlacrittyFromScratchRoute
  '/blog/lattice-backend-ddd-refactor': typeof BlogLatticeBackendDddRefactorRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/build-personal-blog-with-nextjs-and-mdx': typeof BlogBuildPersonalBlogWithNextjsAndMdxRoute
  '/blog/configure-alacritty-from-scratch': typeof BlogConfigureAlacrittyFromScratchRoute
  '/blog/lattice-backend-ddd-refactor': typeof BlogLatticeBackendDddRefactorRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/build-personal-blog-with-nextjs-and-mdx': typeof BlogBuildPersonalBlogWithNextjsAndMdxRoute
  '/blog/configure-alacritty-from-scratch': typeof BlogConfigureAlacrittyFromScratchRoute
  '/blog/lattice-backend-ddd-refactor': typeof BlogLatticeBackendDddRefactorRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/build-personal-blog-with-nextjs-and-mdx'
    | '/blog/configure-alacritty-from-scratch'
    | '/blog/lattice-backend-ddd-refactor'
    | '/sitemap/xml'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/build-personal-blog-with-nextjs-and-mdx'
    | '/blog/configure-alacritty-from-scratch'
    | '/blog/lattice-backend-ddd-refactor'
    | '/sitemap/xml'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/blog/build-personal-blog-with-nextjs-and-mdx'
    | '/blog/configure-alacritty-from-scratch'
    | '/blog/lattice-backend-ddd-refactor'
    | '/sitemap/xml'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogBuildPersonalBlogWithNextjsAndMdxRoute: typeof BlogBuildPersonalBlogWithNextjsAndMdxRoute
  BlogConfigureAlacrittyFromScratchRoute: typeof BlogConfigureAlacrittyFromScratchRoute
  BlogLatticeBackendDddRefactorRoute: typeof BlogLatticeBackendDddRefactorRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/lattice-backend-ddd-refactor': {
      id: '/blog/lattice-backend-ddd-refactor'
      path: '/blog/lattice-backend-ddd-refactor'
      fullPath: '/blog/lattice-backend-ddd-refactor'
      preLoaderRoute: typeof BlogLatticeBackendDddRefactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/configure-alacritty-from-scratch': {
      id: '/blog/configure-alacritty-from-scratch'
      path: '/blog/configure-alacritty-from-scratch'
      fullPath: '/blog/configure-alacritty-from-scratch'
      preLoaderRoute: typeof BlogConfigureAlacrittyFromScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/build-personal-blog-with-nextjs-and-mdx': {
      id: '/blog/build-personal-blog-with-nextjs-and-mdx'
      path: '/blog/build-personal-blog-with-nextjs-and-mdx'
      fullPath: '/blog/build-personal-blog-with-nextjs-and-mdx'
      preLoaderRoute: typeof BlogBuildPersonalBlogWithNextjsAndMdxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogBuildPersonalBlogWithNextjsAndMdxRoute:
    BlogBuildPersonalBlogWithNextjsAndMdxRoute,
  BlogConfigureAlacrittyFromScratchRoute:
    BlogConfigureAlacrittyFromScratchRoute,
  BlogLatticeBackendDddRefactorRoute: BlogLatticeBackendDddRefactorRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
